--[[
	Main Lua script. This is needed to run all scripts in the editor.
	Generated by the engine on project creation.
	DON'T CHANGE unless you know what you are doing!
--]]
-- The engine looks for these three functions.
-- Please add your code inside of the init, update, and render functions as needed.

main = { 
	[1] = { 
		init = function() --[[ Initialize global state variables here ]] end
	}, 
	[2] = { 
		update = function() --[[ Main Lua Update function ]] end
	}, 
	[3] = { 
		render = function() --[[ Main Lua Render function ]] end
	}, 
}
