--[[
	Main Lua script. This is needed to run all scripts in the editor.
	Generated by the engine on project creation.
--]]
-- The engine looks for these three functions.
-- Please add your code inside of the init, update, and render functions as needed.

main = { 
	[1] = { 
		--[[ Initialize global state variables here ]]
		init = function() 
			math.randomseed(os.time())
			gStateStack = StateStack()
			local title = TitleState:Create( { stack = gStateStack } )
			gStateStack:changeState(title:GetState())
			Music.setVolume(20)
		end
	}, 
	[2] = { 
		--[[ Main Lua Update function ]]
		update = function()
			if gStateStack then
				gStateStack:update(F_DeltaTime())
			end
		end
	}, 
	[3] = { 
		--[[ Main Lua Render function ]]
		render = function() end
	}, 
}
