--[[
	Main Lua script. This is needed to run all scripts in the editor.
	Generated by the engine on project creation.
--]]
-- The engine looks for these three functions.
-- Please add your code inside of the init, update, and render functions as needed.

main = { 
	[1] = { 
		--[[ Initialize global state variables here ]]
		init = function() 
			math.randomseed(os.time())
		end
	}, 
	[2] = { 
		--[[ Main Lua Update function ]]
		update = function()

		end
	}, 
	[3] = { 
		--[[ Main Lua Render function ]]
		render = function() end
	}, 
}
